Repository ReGLOSS/Trackery-BackAPIServer, pull requests merged in 2025-07, with the labels that each got.

#66 Feature/db sql 수정
  src/main/resources/data/0.1 table/BackAPISERVER_2025_05_29.sql
  src/main/resources/data/0.1 table/BackAPISERVER_2025_07_01.sql
  src/main/resources/data/0.2 insert_default/insert_default_data_2025_07_01.sql
Labels: documentation

#67 이미지 저장 구조 변경
  src/main/java/com/trackery/trackerybackapiserver/domain/album/controller/AlbumController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageUploadController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/dto/ImageThumbnailDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageS3Service.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageUploadService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/location/controller/LocationController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/user/service/UserService.java
  src/test/java/com/trackery/trackerybackapiserver/domain/album/controller/AlbumControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageUploadControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/service/ImageS3ServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/service/ImageServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/service/ImageUploadServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/location/controller/LocationControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/user/service/UserServiceTest.java
Labels: enhancement

#73 Feature/tag 뷰어
  src/main/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/dto/ImageDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/service/TagService.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/controller/ImageControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/service/ImageServiceTest.java
Labels: enhancement

#76 Issue/#74
  .gitignore
  src/main/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageS3Service.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageService.java
  src/test/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumServiceTest.java
Labels: bug

#77 Feature/태그 기본 태그 자동추가 및 일괄삭제
  src/main/java/com/trackery/trackerybackapiserver/domain/image/dto/ImageUpdateRequestDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/location/controller/LocationController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/location/dto/LocationNameResponseDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/location/service/LocationService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/controller/TagController.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/dto/TagDateRequestDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/dto/TagDefaultRequestDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/dto/TagUpdateRequestDto.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/entity/ImageTag.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/entity/Tag.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/mapper/TagMapper.java
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/service/TagService.java
  src/main/resources/mapper/TagMapper.xml
  src/test/java/com/trackery/trackerybackapiserver/domain/location/controller/LocationControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/location/service/LocationServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/tag/controller/TagControllerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/tag/service/TagServiceTest.java
Labels: enhancement

#80 리프레시 토큰으로 액세스토큰이 자동으로 재발급 되지 않는 문제 수정
  src/main/java/com/trackery/trackerybackapiserver/config/RedisConfig.java
  src/main/java/com/trackery/trackerybackapiserver/config/filter/JwtResolverFilter.java
  src/main/java/com/trackery/trackerybackapiserver/domain/jwt/service/JwtRedisService.java
  src/test/java/com/trackery/trackerybackapiserver/domain/jwt/service/JwtRedisServiceTest.java
Labels: bug

#82 이미지 삭제 시 앨범 관련 기능 정보 처리
  src/main/java/com/trackery/trackerybackapiserver/domain/album/event/AlbumEventListener.java
  src/main/java/com/trackery/trackerybackapiserver/domain/album/event/AlbumImageEditEvent.java
  src/main/java/com/trackery/trackerybackapiserver/domain/album/mapper/AlbumMapper.java
  src/main/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumService.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/event/ImageDeleteEvent.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/event/ImageEventListener.java
  src/main/java/com/trackery/trackerybackapiserver/domain/image/service/ImageService.java
  src/main/resources/mapper/AlbumMapper.xml
  src/test/java/com/trackery/trackerybackapiserver/domain/album/listener/AlbumEventListenerTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/album/service/AlbumServiceTest.java
  src/test/java/com/trackery/trackerybackapiserver/domain/image/service/ImageServiceTest.java
Labels: bug

#85 refactor/테스트시-이벤트-패키지-제외
  pom.xml
Labels: enhancement

#89 Refactor/태그 삭제 처리
  src/main/java/com/trackery/trackerybackapiserver/domain/tag/service/TagService.java
  src/main/resources/mapper/ImageMapper.xml
  src/test/java/com/trackery/trackerybackapiserver/domain/tag/service/TagServiceTest.java
Labels: bug
